### ISSUE TITLE
store_id missing in the instance creation

### ISSUE THREAD

**Issue by leonwetterich** [notrab/printful-request#9]
Really like the client you provided @notrab . Is it possible to add the store_id parameter to the client? Unfortunately when trying to create the instance with the token there is an error.

Thank you in advance!

**Comment by leonwetterich** [comment]
Found the solution. I copied the module and adjusted it myself but maybe you can update the package 😊. Thank you for doing what you're doing!

`// @ts-nocheck
require("cross-fetch/polyfill");
export class PrintfulClient {
  constructor(token: string | undefined, storeId: string | undefined, options = {}) {
    if (!token) throw new Error("No API key provided");

    const { headers }: any = options;

    this.token = token;

    this.options = {
      baseUrl: "https://api.printful.com",
      ...options,
    };

    this.headers = {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
      'X-PF-Store-Id': storeId,
      ...headers,
    };
  }

  async request({ method, endpoint, data, params = {} }) {
    const { baseUrl } = this.options;
    const headers = this.headers;

    const queryString = Object.keys(params).length
      ? `?${Object.keys(params)
          .map(
            (k) => `${encodeURIComponent(k)}=${encodeURIComponent(params[k])}`
          )
          .join("&")}`
      : "";

    const url = `${baseUrl}/${endpoint}${queryString}`;

    const response = await fetch(url, {
      headers,
      ...(method && { method }),
      ...(data && { body: JSON.stringify(data) }),
    });

    const json = await response.json();

    if (!response.ok) throw json;

    return json;
  }

  get(endpoint, params) {
    return this.request({ endpoint, params });
  }

  post(endpoint, data) {
    return this.request({ method: "POST", endpoint, data });
  }

  put(endpoint, data) {
    return this.request({ method: "PUT", endpoint, data });
  }

  delete(endpoint) {
    return this.request({ method: "DELETE", endpoint });
  }
}

async function request(endpoint, { token, ...rest }) {
  const client = new PrintfulClient(token);

  return client.request({ endpoint, ...rest });
}

module.exports = {
  PrintfulClient,
  request,
};`

**Comment by notrab** [comment]
Hey @leonwetterich 

Would the following work for you? It should be supported by the current package...

```js
const printful = new PrintfulClient("PRINTFUL_API_TOKEN", {
  headers: {
      'X-PF-Store-Id': '...',
  }
});
```

**Comment by leonwetterich** [comment]
Even Better @notrab. This will fix the issue of one guy in [headless-dropshipping-starter-Issue-107](https://github.com/notrab/headless-dropshipping-starter/issues/107) thank you very much!

**Comment by notrab** [comment]
Awesome! Hopefully, we can get that starter updated to use Next.js 13 RSC.
